#############################################################################
# Generated by PAGE version 4.13
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

vTcl:font:add_GUI_font font10 \
"-family {DejaVu Sans Mono} -size 9 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top37
    }
    namespace eval ::widgets::$base {
        set dflt,origin 1
        set runvisible 1
    }
    set site_3_0 $base.can38
    set site_4_0 $site_3_0.fra40
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1366x709
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    canvas $top.can38 \
        -background {#95d6d8} -borderwidth 2 -closeenough 1.0 -height 691 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 1341 
    vTcl:DefineAlias "$top.can38" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.can38
    frame $site_3_0.fra40 \
        -borderwidth 2 -relief groove -background {#7b1ed8} -height 65 \
        -highlightcolor black -width 935 
    vTcl:DefineAlias "$site_3_0.fra40" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.fra40
    frame $site_4_0.fra41 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 5 \
        -highlightcolor black -width -35 
    vTcl:DefineAlias "$site_4_0.fra41" "Frame1_1" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_0.mes43 \
        -background {#d9d9d9} -foreground {#ff0000} -highlightcolor black \
        -text {AUTO IMAGE CAPTIONING} -width 362 
    vTcl:DefineAlias "$site_4_0.mes43" "Message1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.fra41 \
        -in $site_4_0 -x 228 -y 114 -width -35 -relwidth 0 -height 5 \
        -relheight 0 -anchor nw -bordermode inside 
    place $site_4_0.mes43 \
        -in $site_4_0 -x 320 -y 10 -width 362 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    canvas $site_3_0.can44 \
        -background {#757bd8} -borderwidth 2 -closeenough 1.0 -height 381 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 521 
    vTcl:DefineAlias "$site_3_0.can44" "Canvas2" vTcl:WidgetProc "Toplevel1" 1
    canvas $site_3_0.can45 \
        -background {#8080ff} -borderwidth 2 -closeenough 1.0 -height 381 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 521 
    vTcl:DefineAlias "$site_3_0.can45" "Canvas3" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar $site_3_0.tPr47
    vTcl:DefineAlias "$site_3_0.tPr47" "TProgressbar1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu50 \
        -takefocus {} -text Speak 
    vTcl:DefineAlias "$site_3_0.tBu50" "TButton2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent53 \
        -background white -font font10 -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent53" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu57 \
        -takefocus {} -text {Gnerate Caption} 
    vTcl:DefineAlias "$site_3_0.tBu57" "TButton1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TButton -background #d9d9d9
    ttk::style configure TButton -foreground #000000
    ttk::style configure TButton -font TkDefaultFont
    ttk::button $site_3_0.tBu58 \
        -takefocus {} -text {Click To Upload An Image} 
    vTcl:DefineAlias "$site_3_0.tBu58" "TButton3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.fra40 \
        -in $site_3_0 -x 190 -y 30 -width 935 -relwidth 0 -height 65 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.can44 \
        -in $site_3_0 -x 20 -y 140 -width 521 -relwidth 0 -height 381 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.can45 \
        -in $site_3_0 -x 800 -y 140 -width 521 -relwidth 0 -height 381 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tPr47 \
        -in $site_3_0 -x 390 -y 550 -width 550 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu50 \
        -in $site_3_0 -x 630 -y 650 -anchor nw -bordermode ignore 
    place $site_3_0.ent53 \
        -in $site_3_0 -x 380 -y 580 -width 566 -relwidth 0 -height 61 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu57 \
        -in $site_3_0 -x 610 -y 510 -anchor nw -bordermode ignore 
    place $site_3_0.tBu58 \
        -in $site_3_0 -x 560 -y 300 -width 219 -relwidth 0 -height 48 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can38 \
        -in $top -x 10 -y 10 -width 1341 -relwidth 0 -height 691 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

